int _putchar(char h);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int T);
int _isalpha(int T);
int print_sign(int Z);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int Z);
void print_times_table(int Z);
